-- Practica 1
DROP DATABASE CENTRO_MEDICO;
CREATE DATABASE CENTRO_MEDICO;
USE CENTRO_MEDICO;

CREATE TABLE CIUDAD
(
COD_C INT PRIMARY KEY,
NOM_C VARCHAR (40)
);

CREATE TABLE HOSPITAL
(
COD_H INT,
NOM_H VARCHAR (40), 
COD_C INT,
PRIMARY KEY (COD_H, NOM_H),
FOREIGN KEY (COD_C) REFERENCES CIUDAD (COD_C)
);

CREATE TABLE ESPECIALIDAD
(
COD_ESP INT PRIMARY KEY,
NOM_ESP VARCHAR(40)
);

CREATE TABLE MEDICO
(
DNI_M INT PRIMARY KEY,
NOM_M VARCHAR (40),
EDAD INT,
SALARIO DECIMAL (10,2),
COD_ESP INT,
COD_H INT,
FOREIGN KEY (COD_ESP) REFERENCES ESPECIALIDAD (COD_ESP),
FOREIGN KEY (COD_H) REFERENCES HOSPITAL (COD_H)
);

INSERT INTO CIUDAD (COD_C, NOM_C) 

VALUES		(01,'BILBAO'),
			(02,'LEIOA'),
			(03,'ERANDIO'),
			(04,'BASAURI'),
			(05,'BARAKALDO');

INSERT INTO HOSPITAL (COD_H, NOM_H, COD_C)

VALUES		(01, 'CRUCES', 05),
    		(02, 'BASAURI', 04),
    		(03, 'BASURTO', 01),
			(04, 'VIRGEN BLANCA', 01),
			(05, 'DOCTOR SAN SEBASTIAN', 01),
    		(06, 'QUIRON', 02);


INSERT INTO ESPECIALIDAD (COD_ESP, NOM_ESP)

VALUES		(01, 'PEDIATRIA'),
    		(02, 'PSICOLOGÍA'),
    		(03, 'NEUROLOGÍA'),
    		(04, 'GINECOLOGÍA');


INSERT INTO MEDICO (DNI_M, NOM_M, EDAD, SALARIO, COD_ESP, COD_H)

VALUES		(111, 'GONZALEZ', 35, 3000.00, 01, 06),
    		(222, 'PÉREZ', 45, 3500.00, 01, 06),
    		(333, 'MARTINEZ', 25.00, 1000, 04, 01),
    		(444, 'GOMEZ', 30, 2500.00, 04, 01),
    		(555, 'PEREZ', 55, 3000.00, 01, 03),
    		(666, 'LLONA', 56, 3000.00, 02, 05),
    		(777, 'MARCOS', 60, 4000.00, 03, 05);

-- 1
SELECT * FROM CIUDAD;
-- 2
SELECT * FROM MEDICO;
-- 3
SELECT NOM_H FROM HOSPITAL;
-- 4 
SELECT NOM_ESP FROM ESPECIALIDAD WHERE COD_ESP = 02;
-- 5
SELECT DNI_M FROM MEDICO WHERE EDAD > 40;
-- 6
SELECT NOM_M FROM MEDICO WHERE EDAD <>40;
-- 7
SELECT NOM_M FROM MEDICO WHERE SALARIO = 3000;
-- 8 
SELECT NOM_H FROM HOSPITAL WHERE COD_C IN(01, 02);
-- 9
SELECT NOM_M FROM MEDICO WHERE COD_ESP=01;
-- 10
SELECT NOM_M FROM MEDICO  WHERE SALARIO BETWEEN 2000.00 AND 3000.00;
-- 11
SELECT NOM_ C FROM CIUDAD WHERE NOM_C LIKE '%B%';
-- 12
SELECT DNI_M, NOM_M, SALARIO FROM MEDICO WHERE COD_H=04;
-- 13
SELECT DNI_M FROM MEDICO WHERE COD_ESP IN(02, 04);
-- 14
SELECT NOM_M FROM MEDICO WHERE COD_ESP=01 AND COD_H=06;
-- 15
SELECT NOM_H FROM HOSPITAL WHERE NOM_H LIKE '%o%';

-- Practica 2
-- 1
SELECT COUNT(*) FROM ESPECIALIDAD;
-- 2
SELECT COUNT(*) FROM MEDICO;
-- 3 
SELECT AVG(EDAD) FROM MEDICO;
-- 4
SELECT SUM(EDAD) FROM MEDICO;
-- 5
SELECT MIN(EDAD) FROM MEDICO;
-- 6
SELECT COUNT(*) FROM CIUDAD;
-- 7 
SELECT SQRT(SALARIO) FROM MEDICO WHERE DNI=222;
-- 8
SELECT MAX(SALARIO) FROM MEDICO;
-- 9 
SELECT DNI_M, NOM_M FROM MEDICO WHERE SALARIO>=3000 ORDER BY EDAD DESC;
-- 10
SELECT COUNT(*) FROM HOSPITAL;
-- 11
SELECT MAX(EDAD) FROM MEDICO;
-- 12
SELECT DNI_M, NOM_M FROM MEDICO WHERE EDAD=30 ORDER BY SALARIO;
-- 13 aun por ver..
SELECT NOM_H, NOM_C FROM HOSPITAL;